workflows:
  native-android:
    name: Snake Game Android (Official Config)
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      android_signing:
        - snake_game_keystore
      vars:
        PACKAGE_NAME: "com.termux.snake"
        GOOGLE_PLAY_TRACK: "internal"
      java: 17
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.android/build-cache
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
    scripts:
      - name: Set Android SDK location
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
          
      - name: Install correct build tools
        script: |
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "build-tools;34.0.0" "platforms;android-33"
          
      - name: Set AAPT2 override for compatibility
        script: |
          echo "android.aapt2Version=8.6.1-11315950" >> gradle.properties
          
      - name: Build Android debug
        script: | 
          ./gradlew assembleDebug --no-daemon --stacktrace
          
      - name: Build Android release (if debug succeeds)
        script: | 
          ./gradlew assembleRelease --no-daemon --stacktrace
          
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
      
    publishing:
      email:
        recipients:
          - jd21hinman@gmail.com
        notify:
          success: true
          failure: true

  # Alternative minimal workflow for troubleshooting
  android-minimal:
    name: Snake Game Minimal Test
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      java: 17
    scripts:
      - name: Set Android SDK location
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
          
      - name: Test Kotlin compilation only
        script: |
          ./gradlew compileDebugKotlin --no-daemon --stacktrace
          
    publishing:
      email:
        recipients:
          - jd21hinman@gmail.com
        notify:
          success: true
          failure: false