workflows:
  android-simple:
    name: Snake Game Simple Build
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      java: 17
    cache:
      cache_paths:
        - ~/.gradle/caches
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
          
      - name: Build debug APK
        script: |
          cd $CM_BUILD_DIR
          chmod +x gradlew
          ./gradlew assembleDebug
          
    artifacts:
      - app/build/outputs/**/*.apk
      
    publishing:
      email:
        recipients:
          - jd21hinman@gmail.com
        notify:
          success: true
          failure: true