workflows:
  native-android:
    name: Snake Game Android (Fixed)
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        PACKAGE_NAME: "com.termux.snake"
      java: 17
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.android/build-cache
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
    scripts:
      - name: Set Android SDK location
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
          
      - name: Install correct build tools for AAPT2 compatibility
        script: |
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "build-tools;34.0.0" "platforms;android-33"
          
      - name: Debug wrapper and build
        script: | 
          cd $CM_BUILD_DIR
          echo "=== Debugging Gradle Wrapper Issue ==="
          echo "Current directory: $(pwd)"
          echo "Gradle wrapper jar exists: $(ls -la gradle/wrapper/gradle-wrapper.jar)"
          echo "Gradlew script exists: $(ls -la gradlew)"
          echo "Trying system Gradle first..."
          gradle assembleDebug --no-daemon --stacktrace
          
    artifacts:
      - app/build/outputs/**/*.apk
      
    publishing:
      email:
        recipients:
          - jd21hinman@gmail.com
        notify:
          success: true
          failure: true

  android-wrapper-regen:
    name: Snake Game Android (Wrapper Regeneration)
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        PACKAGE_NAME: "com.termux.snake"
      java: 17
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.android/build-cache
    scripts:
      - name: Set Android SDK location
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
          
      - name: Install correct build tools for AAPT2 compatibility
        script: |
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "build-tools;34.0.0" "platforms;android-33"
          
      - name: Regenerate Gradle wrapper on Codemagic
        script: |
          cd $CM_BUILD_DIR
          gradle wrapper --gradle-version=8.4
          chmod +x gradlew
          
      - name: Build debug APK with regenerated wrapper
        script: | 
          cd $CM_BUILD_DIR
          ./gradlew assembleDebug --no-daemon --stacktrace
          
    artifacts:
      - app/build/outputs/**/*.apk
      
    publishing:
      email:
        recipients:
          - jd21hinman@gmail.com
        notify:
          success: true
          failure: true

  android-no-wrapper:
    name: Snake Game Android (No Wrapper)
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        PACKAGE_NAME: "com.termux.snake"
        GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8"
      java: 17
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.android/build-cache
    scripts:
      - name: Set Android SDK location
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
          
      - name: Install correct build tools for AAPT2 compatibility
        script: |
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "build-tools;34.0.0" "platforms;android-33"
          
      - name: Build debug APK using system Gradle
        script: | 
          cd $CM_BUILD_DIR
          gradle assembleDebug --no-daemon --stacktrace --info
          
    artifacts:
      - app/build/outputs/**/*.apk
      
    publishing:
      email:
        recipients:
          - jd21hinman@gmail.com
        notify:
          success: true
          failure: true