workflows:
  android-no-wrapper:
    name: Snake Game Android (No Wrapper)
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        PACKAGE_NAME: "com.termux.snake"
        GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8"
      java: 17
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.android/build-cache
    scripts:
      - name: Set Android SDK location
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
          
      - name: Install correct build tools for AAPT2 compatibility
        script: |
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "build-tools;34.0.0" "platforms;android-33"
          
      - name: Verify Gradle installation
        script: |
          gradle --version
          echo "Project directory contents:"
          ls -la $CM_BUILD_DIR
          
      - name: Build debug APK using system Gradle
        script: | 
          cd $CM_BUILD_DIR
          gradle assembleDebug --no-daemon --stacktrace --info
          
    artifacts:
      - app/build/outputs/**/*.apk
      
    publishing:
      email:
        recipients:
          - jd21hinman@gmail.com
        notify:
          success: true
          failure: true