workflows:
  native-android:
    name: Snake Game Android (Fixed)
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        PACKAGE_NAME: "com.termux.snake"
      java: 17
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.android/build-cache
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
    scripts:
      - name: Set Android SDK location
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
          
      - name: Install correct build tools for AAPT2 compatibility
        script: |
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "build-tools;34.0.0" "platforms;android-33"
          
      - name: Debug wrapper and build
        script: | 
          cd $CM_BUILD_DIR
          echo "=== Debugging Gradle Wrapper Issue ==="
          echo "Current directory: $(pwd)"
          echo "Gradle wrapper jar exists: $(ls -la gradle/wrapper/gradle-wrapper.jar)"
          echo "Gradlew script exists: $(ls -la gradlew)"
          echo "Trying system Gradle first..."
          gradle assembleDebug --no-daemon --stacktrace
          
    artifacts:
      - app/build/outputs/**/*.apk
      
    publishing:
      email:
        recipients:
          - jd21hinman@gmail.com
        notify:
          success: true
          failure: true

  android-test-workflow:
    name: Snake Game Testing
    max_build_duration: 30
    instance_type: linux_x2
    environment:
      java: 17
    scripts:
      - name: Run unit tests
        script: |
          cd $CM_BUILD_DIR
          ./gradlew test
          
      - name: Run instrumentation tests
        script: |
          cd $CM_BUILD_DIR  
          ./gradlew connectedAndroidTest
          
    artifacts:
      - app/build/reports/**
      - app/build/test-results/**
      
    publishing:
      email:
        recipients:
          - developer@termux.com
        notify:
          success: false
          failure: true